# Plugins
plugins:
- jekyll-sitemap
safe: false
future: true

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'original_readme.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Virtual Data Science Africa Kimberley 2021"
email: "info@datascienceafrica.org"
description: "Virtual DSA Kimberley 2021"
baseurl: "/dsa2021kimberley"
url: "http://www.datascienceafrica.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-80484960-1"
googleAnalyticsSiteUrl: "datascienceafrica.org"
venuName: "Sol Plaatje University"
venuLogo: "spu_logo.png"
sitetheme: "Theme: Women and Data In Africa"
# TODO - setup site verification
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Data Science Africa"
organizerAlternateName: "Data Science Africa"
organizerDescription: "Data from a vast array of sources is becoming available in many African countries. Machine learning and analysis are being applied to solve real problems on the ground."
organizerEmail: "info@datascienceafrica.org"
organizerLogo: "/img/seo/dsa-logo.png"
organizerLink: "http://datascienceafrica.org/"

# Head
metaKeywords: "event, data science, africa, dsa, programming, machine learning, developers"
twitterAccount: "@dsa_org"

# Documents
c4pUrl: ""
c4sponsorsUrl: "mailto:info@datascienceafrica.org?subject=Event%20Sponsorship%20for%20DSA%202021%20Kimberley"


# Navigation
navigationLinks:
 # - {permalink: "/", text: "Home"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/gallery/", text: "Gallery"}
 - {permalink: "/news/", text: "News"}
# - {permalink: "/team/", text: "Team"}
 #- {permalink: "/logistics/", text: "Logistics"}
 #- {permalink: "/hackathon/", text: "Virtual Field Work"}
 - {link: "http://www.datascienceafrica.org#events", text: "Past Meetings"}
 - {link: "http://www.datascienceafrica.org", text: "DSA Org"}
# bottomNavigationLinks:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
# rightNavigationButtons:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "image 2.jpg"
heroTitle: "Virtual DSA <typeout> 2021"
eventDate: "4<sup>th</sup> - 8<sup>th</sup> October, 2021"
typeoutTextValues: '"", "Event", "Field Work", "Summer School", "Workshop"'
typeoutFallback: "Event"
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}
#heroImage: "makerere-main.jpg"
# Photo by Damian Patkowski on Unsplash
#heroTitle: "Virtual Data Science Africa"
# heroTitle: "Data Science Africa Kampala 2020<typeout>"
#eventDate: "July 24 - Aug 1, 2020"
startRegistration: "June 20, 2021"
endRegistration: "July 28, 2021"
heroButtons:
 - {permalink: "/tbd", text: "REGISTER NOW"}
 # - {permalink: "/tbd", text: "Submit Workshop Abstract"}
prepLinks:
 - {link: "https://jupyter.readthedocs.io/en/latest/", text: "Getting started with Jupyter notebooks"}
 - {link: "https://scipy-lectures.org", text: "Introductory SciPy lectures"}
# - {link: "https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html", text: "Pandas 101"}
 - {link: "https://colab.research.google.com/notebooks/intro.ipynb", text: "Colab basics"}
 - {link: "https://github.com/datsciafrica/presentations", text: "Previous DSA events material"}

# About Block
aboutTitle: "Highlights"
aboutBlock:
 - {title: "Embedded ML - Tiny ML", image: "Embedded ML-TinyML.png", text: "TinyML is a cutting-edge field that brings the transformative power of machine learning (ML) to the performance- and power-constrained domain of tiny devices and embedded systems. Successful deployment in this field requires intimate knowledge of applications, algorithms, hardware, and software." }
 - {title: "Summer School", image: "conference.jpg", text: "In the tradition of previous Data Science Africa  events, a summer school on machine learning and data science will be held prior to the main workshop. This summer school will target graduate students, researchers and professionals working with huge amounts of data or unique datasets.
" }
 - {title: "Workshop", image: "workshop.jpg", text: "The workshop will be organized around paper presentations and interactive panel discussions. The theme for the workshop is Women and Data in Africa. We want to highlight the work of women data scientists and increase representation of women in Data Science in Africa. We strongly encourage the participation of women from across the continent." }

# Statistic Block
statisticBlockImage: "The-Big-Hole-1-1.jpg"
statisticBlock:
 - {count: "30", specialCharacter: "+", info: "African countries", detail: "participation"}
 - {count: "50", specialCharacter: "+", info: "topics", detail: "covered"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from all over the world"}

# Latest News Block
latestNewsTitle: "Latest news"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Conference Hall"
eventLocationLink: ""
eventStreetAddress: "AoE"
eventAddressLocality: "Kimberley"
eventAddressLocalityRegion: "Kimberley"
eventPostalCode: "00000"
eventAddressCountry: "South Africa"
eventStartTime: "2020-06-22T08:00"
eventDoorTime: "08:30"
eventEndTime: "2020-06-26T17:00"
eventPlaceCoordinates: "0.3476, 32.5825"
mapCenterCoordinates: "0.3476, 32.5825"
mapMobileCenterCoordinates: "0.3476, 32.5825"

# Partners Block
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "BECOME A SPONSOR"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: ""
subscribeInfo: "Registration will be open soon. Stay tuned!"
#Gallery
gallerylinks:
 - {imagename: "1.jpg", thumbnail: "1.jpg",  datasubhtml: "Native Minds Tour Group", datasubparagraph: ""}
 - {imagename: "2.jpg", thumbnail: "2.jpg", datasubhtml: "", datasubparagraph: ""}
 - {imagename: "3.jpg", thumbnail: "3.jpg", datasubhtml: "", datasubparagraph: ""}
 - {imagename: "4.jpg", thumbnail: "4.jpg", datasubhtml: "Big Hole Kimberley", datasubparagraph: ""}
 - {imagename: "5.jpg", thumbnail: "5.jpg", datasubhtml: "Big Hole Complex Kimberley", datasubparagraph: ""}
 - {imagename: "6.jpg", thumbnail: "6.jpg", datasubhtml: "Big Hole Complex Kimberley", datasubparagraph: ""}
 - {imagename: "7.jpg", thumbnail: "7.jpg", datasubhtml: "Cricket", datasubparagraph: ""}
 - {imagename: "8.jpg", thumbnail: "8.jpg", datasubhtml: "Diamond", datasubparagraph: ""}
 - {imagename: "9.jpg", thumbnail: "9.jpg", datasubhtml: "Edge of Kimberley Mine, 1872, shows 15 road ways that bisected the diggings", datasubparagraph: ""}
 - {imagename: "10.jpg", thumbnail: "10.jpg", datasubhtml: "Fishing at Modderrivier", datasubparagraph: ""}
 - {imagename: "11.jpg", thumbnail: "11.jpg", datasubhtml: "Fly Fishing", datasubparagraph: ""}
 - {imagename: "12.jpg", thumbnail: "12.jpg", datasubhtml: "Galeshewe Uprising Monument", datasubparagraph: ""}
 - {imagename: "13.jpg", thumbnail: "13.jpg", datasubhtml: "kimberley", datasubparagraph: ""}
 - {imagename: "14.jpg", thumbnail: "14.jpg", datasubhtml: "kimberley", datasubparagraph: ""}
 - {imagename: "15.jpg", thumbnail: "15.jpg", datasubhtml: "Kimberley McGregor museum", datasubparagraph: ""}
 - {imagename: "16.jpg", thumbnail: "16.jpg", datasubhtml: "Magersfontein Museum", datasubparagraph: ""}
 - {imagename: "17.jpg", thumbnail: "17.jpg", datasubhtml: "Mattanu Private Game Reserve", datasubparagraph: ""}
 - {imagename: "18.jpg",thumbnail: "18.jpg", datasubhtml: "Mokala Tsessebe", datasubparagraph: ""}
 - {imagename: "19.jpg", thumbnail: "19.jpg", datasubhtml: "Mokala Wild life Zebra", datasubparagraph: ""}
 - {imagename: "20.jpg", thumbnail: "20.jpg",  datasubhtml: "MSICC", datasubparagraph: ""}
 - {imagename: "21.jpg", thumbnail: "21.jpg", datasubhtml: "Rock Painting", datasubparagraph: ""}
 - {imagename: "22.jpg", thumbnail: "22.jpg", datasubhtml: "Sol Plaatje Museum and Literature", datasubparagraph: ""}
# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=dsa_org", icon: "twitter"}
 - {link: "https://facebook.com/DataScienceAfrica", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.datascienceafrica.org", text: "DSA Organization"}
 -
  title: "Contacts"
  links:
#   - {link: "mailto:dsakampala2020@gmail.com", text: "dsakampala2020@gmail.com"}
   - {link: "mailto:info@datascienceafrica.org", text: "info@datascienceafrica.org"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Updates"
blogCommentsEnabled: false
discusShortName: "dsadiscuss"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "The last few years have witnessed an explosion in the quantity and variety of data available in Africa, produced either as a by-product of digital services, from sensors or measuring devices, satellites and from many other sources. A number of practical fields have been transformed by the ability to collect large volumes of data: for example, bioinformatics with the development of high throughput sequencing technology capable of measuring gene expression in cells, or agriculture with the widespread availability of high quality remote sensing data. For other data sources – such as mobile phone usage records from telecoms operators, which can be used to measure population movement and economic activity – we are just beginning to understand the practical possibilities."


# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsCards:
 - {title: "Virtual Conference Technology", information: 'Zoom details will be shared with registered participants directly.'}
 - {title: "Q & A", information: 'TBD'}
 - {title: "Chat and Collaboration", information: 'TBD'}
directionDetailsWideCards:
 -
  title: "Other Details"
  subCards:
   -
    title: "Registration"
    links:
     - {permalink: "/tbd", text: "Summer school"}
     - {permalink: "/tbd", text: "Workshop abstract submission"}
   -
    title: "Materials"
    links:
     - {link: "https://github.com/datsciafrica/presentations", text: "Summer school lectures"}
     - {link: "https://github.com/datsciafrica/presentations", text: "Datasets"}
     - {link: "https://www.youtube.com/channel/UCkB0DCJZjJX6fdEZspidC9w/feed", text: "Past video materials"}
     - {link: "http://www.datascienceafrica.org/covid19/", text: "COVID related information"}

# Hackathon
hackathonTitle: "Virtual Field Work"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Virtual Field Work Projects"
hackathonRows:
 - {title: "Crop disease monitoring", image: "cropMonitoringFields.png", details: "The objective of this field work is to provide participants with hands-on experience in crop diseae monotoring using mobile phone and spectrometry. This will be based on a research project aimed at developing experimental tools and techniques needed for the surveillance and detection of serious viral crop diseases, which affect Uganda and the East African region. The following core areas have been investigated on and will be demonstrated during the field study. These include <ol type='circle'><li>mobile data collection in the field</li><li> diagnosis of crop disease in the field based on crop images </li><li> mobile phone applications for auto pest and disease count</li><li>Spectrometry of early disease dectection</li></ol>"} 
 - {title: "Air pollution monitoring", image: "AirQoFieldwork.png", details: "The objective of this field work is to provide participants with hands-on experience on building an air quality IoT device. The session will start with an introduction to air pollution, its effects, different types of pollutants and air quality sensing technologies. Participants will be able to prototype and deploy an IoT device that is capable of collecting air quality data and transmitting it in real-time to a cloud-based platform for analysis."}


